### ISSUE TITLE
Example with Xamarin.Forms

### ISSUE THREAD

**Issue by homerokzam** [woutercx/Xamarin-EstimoteBeacons#3]
Do you have any example using Xamarin.Forms with Estimote?

**Comment by woutercx** [comment]
No I don't, but here's a couple of resources that might help you out:
https://forums.xamarin.com/discussion/46902/xamarin-forms-and-estimote-sdk
https://components.xamarin.com/gettingstarted/estimotesdkios
https://blog.xamarin.com/adding-real-world-context-with-estimote-beacons-and-stickers/
